let arrLang = {
    'ru': {
        'menu': 'Меню',
        'main': 'Главная',
        'about': 'Обо мне',
        'welup': 'Я TheFreo,',
        'welun': ' Я начинающий программист. Люблю сидеть дома и смотреть аниме :-) Сейчас изучаю ReactJS и TypeScript.',
        'bio': 'Кто я?',
        'skills': 'Навыки',
        'devices': 'Девайсы',
        'pc': 'Основной ПК',
        'lap': 'Ноутбук (MateBook D14)',
        'os': 'Система:',
        'cpu': 'Процессор:',
        'gpu': 'Видеокарта:',
        'ram': 'ОЗУ:',
        'slap': 'Второй ноутбук (Macbook Pro 13 2014)',
        'name': 'Имя: Артём',
        'brith': 'День рождения: 15.06.2005 (Осталось ',
        'brith2': ' дней)',
        'country': 'Страна: Россия (мечтаю переехать в Японию или Европу)',
        'city': 'Город: Новосибирск (Родной: Сургут)',
        'stud': 'Учусь: СибГУТИ',
        'langu': 'Языки: Русский, Английский (30%), Украинский (70%)',
        'listen': 'Слушаю: Рок (Любой), IDM, Ambient',
        'cont': 'Контакты',
        'morning': 'Доброе утро!',
        'afternoon': 'Добрый день!',
        'evening': 'Добрый вечер!',
        'night': 'Доброй ночи!',
        'dev': '©2024, Разработано ',
        'today': 'Сегодня!'
    },
    'en': {
        'menu': 'Menu',
        'main': 'Main',
        'about': 'About me',
        'welup': "I'm TheFreo,",
        'welun': "I'm an aspiring programmer. I like to sit at home and watch anime :-) At the moment I am studying ReactJS and TypeScript.",
        'bio': 'Who Am I?',
        'skills': 'Skills',
        'devices': 'Devices',
        'pc': 'Main PC',
        'lap': 'Laptop (MateBook D14)',
        'slap': 'Second laptop (Macbook Pro 13 2014)',
        'os': 'OS:',
        'cpu': 'CPU:',
        'gpu': 'GPU:',
        'ram': 'RAM:',
        'name': 'Name: Artem',
        'brith': 'Brithday: 15.06.2005 (through ',
        'brith2': ' days)',
        'country': 'Counrty: Russia (dream: Japan or Europe)',
        'city': 'City: Novosibirsk (Hometowm: Surgut)',
        'stud': 'Studying: SibSUTIS',
        'langu': 'Languages: Russia, English (30%), Ukrainian (70%)',
        'listen': 'Listen: Rock (Any), IDM, Ambient',
        'cont': 'Contacts',
        'morning': 'Good morning!',
        'afternoon': 'Good afternoon!',
        'evening': 'Good evening!',
        'night': 'Good night!',
        'dev': '©2024, Crafted by ',
        'today': 'Today!'
    }
};